選手の試合結果詳細データを作る
===

```{r}
library(dplyr)
library(data.table)
library(rvest)
library(stringr)
```


```{r}
member_table <- read.csv("year_member_list.csv")

## チーム
central_team_list <- c("G", "T", "C", "D", "DB", "Ys", "YB")
pacific_team_list <- c("H", "Bs", "F", "L", "E", "M")

member_table_for_url <- 
  member_table %>% 
  select(year, team, 背番, 名前)

size_member_table_for_url <- 
  member_table_for_url %>% dim(.) %>% .[[1]]

player_data <- data.frame()

for(num in 1:size_member_table_for_url){
  paste("num: ", num, " all: ", size_member_table_for_url) %>% 
    print
  
  player <- member_table_for_url[num,]
  league_name <- ifelse(player$team %in% central_team_list, "Central", "Pacific")
  url <- paste("http://lcom.sakura.ne.jp/NulData/",
               player$year, 
               "/",
               league_name,
               "/",
               player$team, 
               "/f/", 
               player$背番, 
               "_stat_all.htm",
               sep = ""
              )
  
  ## htmlのダウンロード 
  ### ページが存在しなければ、次の行に飛ぶ
  html <- try(read_html(url), silent = TRUE)
  if(class(html)=="try-error"){
    next()
  }
  
  ## htmlからテーブルを抜き出す
  html.table <- 
    html %>% html_node(xpath="/html/body/div/table[4]")
  ## ページはあるけどテーブルがない場合がある
  ## http://lcom.sakura.ne.jp/NulData/2015/Central/T/f/45_stat_all.htm
  atbat_result_table <- try(html_table(html.table, fill=TRUE))
  ## ダメだったら次
  if(class(atbat_result_table)=="try-error"){
    next()
  }
  
  ## 変な列を除く
  atbat_result_table <-
    atbat_result_table[,1:18] 
  
  ## 列名の設定 
  column_names <- c("日付", "対戦", "球場", "出場", "守備",
               "被交代選手", "要因", "交代選手", "打数", "得点",
               "安打", "本塁", "打点", "盗塁", "盗塁死", 
               "失策", "通算", "詳細")
  atbat_result_table %>% setnames(column_names)
  
  ## 変な行を除く
  atbat_result_table <-
    atbat_result_table %>%
    filter(日付 != "日付")  %>% 
    filter(!str_detect(日付, "■")) 
  
  ## 詳細の行のカンマを、別の文字に置き換える
  atbat_result_table <-
    atbat_result_table %>%
    mutate(詳細 = str_replace_all(詳細, "\r\n", "")) %>% 
    mutate(詳細 = str_replace_all(詳細, ",", "_"))
  
  ## 選手の名前を加える
  atbat_result_table <-
    atbat_result_table %>% 
    mutate(名前 = player$名前) %>% 
    mutate(背番 = player$背番) %>% 
    mutate(team = as.character(player$team)) %>% 
    mutate(year = as.character(player$year))
  
  ## 結合する
  player_data <- 
    rbind(player_data, atbat_result_table)
  Sys.sleep(1)
}

## 日付を作る
player_data <- 
  player_data %>% 
  mutate(date = as.Date(paste(year, 日付, sep="/")))

write.csv(player_data, "player_gameresult.csv", 
          quote=FALSE, row.names=FALSE)

```


